import type { WalletInfo, Transaction, Goal, ChatMessage } from './types/index.js';

interface AppStore {
  wallet: WalletInfo | null;
  transactions: Transaction[];
  goals: Goal[];
  chatHistory: ChatMessage[];
}

export const store: AppStore = {
  wallet: null,
  transactions: [
    {
      id: 'tx-1',
      type: 'sent',
      amountUsdc: 250,
      amountUgx: 937500,
      rate: 3750,
      recipientName: 'Maama',
      recipientPhone: '+256712345678',
      recipientNetwork: 'MTN',
      status: 'completed',
      purpose: 'Family Support',
      stellarTxHash: 'a1b2c3d4e5f6',
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'tx-2',
      type: 'sent',
      amountUsdc: 1200,
      amountUgx: 4500000,
      rate: 3750,
      recipientName: 'Ssekandi',
      recipientPhone: '+256701234567',
      recipientNetwork: 'AIRTEL',
      status: 'completed',
      purpose: 'Construction Milestone',
      stellarTxHash: 'b2c3d4e5f6a7',
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: 'tx-3',
      type: 'sent',
      amountUsdc: 150,
      amountUgx: 562500,
      rate: 3750,
      recipientName: 'Sarah',
      recipientPhone: '+256772345678',
      recipientNetwork: 'MTN',
      status: 'pending',
      purpose: 'School Fees',
      createdAt: new Date(Date.now() - 172800000).toISOString(),
    },
    {
      id: 'tx-4',
      type: 'sent',
      amountUsdc: 4550,
      amountUgx: 17062500,
      rate: 3750,
      recipientName: 'Sula Contractors',
      status: 'completed',
      purpose: 'Material Supply',
      stellarTxHash: 'c3d4e5f6a7b8',
      createdAt: new Date(Date.now() - 345600000).toISOString(),
    },
    {
      id: 'tx-5',
      type: 'received',
      amountUsdc: 12.50,
      amountUgx: 46875,
      rate: 3750,
      recipientName: 'Refund — Kotani Pay',
      status: 'completed',
      purpose: 'Failed TX Reversal',
      stellarTxHash: 'd4e5f6a7b8c9',
      createdAt: new Date(Date.now() - 432000000).toISOString(),
    },
    {
      id: 'tx-6',
      type: 'sent',
      amountUsdc: 340,
      amountUgx: 1275000,
      rate: 3750,
      recipientName: "Junior's School",
      recipientPhone: '+256783456789',
      recipientNetwork: 'MTN',
      status: 'failed',
      purpose: 'Education',
      createdAt: new Date(Date.now() - 518400000).toISOString(),
    },
  ],
  goals: [
    {
      id: 'goal-1',
      title: 'Build My Home — Wakiso',
      description: 'Three-bedroom house construction in Wakiso district',
      targetAmountUgx: 150000000,
      savedAmountUgx: 97500000,
      targetDate: '2026-12-31',
      category: 'home',
      status: 'active',
      createdAt: new Date(Date.now() - 2592000000).toISOString(),
      milestones: [
        { id: 'ms-1', title: 'Foundation', targetAmountUgx: 30000000, description: 'Land clearing and foundation pouring', completed: true, completedAt: '2026-03-15' },
        { id: 'ms-2', title: 'Walling', targetAmountUgx: 40000000, description: 'Wall construction and roofing prep', completed: true, completedAt: '2026-05-20' },
        { id: 'ms-3', title: 'Roofing', targetAmountUgx: 35000000, description: 'Roof installation and ceiling', completed: false },
        { id: 'ms-4', title: 'Interior', targetAmountUgx: 45000000, description: 'Plumbing, electrical, finishing', completed: false },
      ],
    },
    {
      id: 'goal-2',
      title: "Junior's Education Fund",
      description: 'School fees savings for 2027 academic year',
      targetAmountUgx: 12000000,
      savedAmountUgx: 4500000,
      targetDate: '2027-01-15',
      category: 'education',
      status: 'active',
      createdAt: new Date(Date.now() - 864000000).toISOString(),
      milestones: [
        { id: 'ms-5', title: 'Term 1 Fees', targetAmountUgx: 4000000, description: 'First term tuition', completed: false },
        { id: 'ms-6', title: 'Term 2 Fees', targetAmountUgx: 4000000, description: 'Second term tuition', completed: false },
        { id: 'ms-7', title: 'Term 3 Fees', targetAmountUgx: 4000000, description: 'Third term tuition', completed: false },
      ],
    },
  ],
  chatHistory: [
    {
      role: 'assistant',
      content: "Hi! I'm Kanzu, your AI financial companion. I can help you send money to Uganda, track your savings goals, answer questions about your finances, and more. What would you like to do today?",
      timestamp: new Date().toISOString(),
    },
  ],
};
